'use client'

import { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase'
import { useRouter } from 'next/navigation'
import Link from 'next/link'

export default function Settings() {
  const [step, setStep] = useState(1) // 1: Enter URL, 2: Review Profile
  const [url, setUrl] = useState('')
  const [screenshot, setScreenshot] = useState('')
  const [screenshotName, setScreenshotName] = useState('')
  
  // Step 2 Form States
  const [name, setName] = useState('')
  const [description, setDescription] = useState('')
  const [competitors, setCompetitors] = useState('')
  const [subreddits, setSubreddits] = useState('')
  const [keywords, setKeywords] = useState('')
  const [usps, setUsps] = useState('')
  const [problemSolved, setProblemSolved] = useState('')
  const [visualDescription, setVisualDescription] = useState('')
  
  const [icpInfo, setIcpInfo] = useState<any>(null)
  const [isNiche, setIsNiche] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')
  const router = useRouter()

  // Load existing product on mount to skip to Step 2
  useEffect(() => {
    // 1. Try to load preview context generated by Home URL scan
    const storedPreview = localStorage.getItem('czero_product_preview')
    if (storedPreview) {
      try {
        const product = JSON.parse(storedPreview)
        setUrl(product.url)
        setName(product.name || '')
        setDescription(product.description || '')
        setCompetitors(product.competitor_names ? product.competitor_names.join(', ') : '')
        setSubreddits(product.subreddit_list ? product.subreddit_list.join(', ') : 'SaaS, startups')
        setKeywords(product.keywords ? product.keywords.join(', ') : '')
        
        const icp = product.icp || {}
        setIsNiche(icp.is_niche || false)
        setUsps(icp.usps ? mtusps(icp.usps) : '')
        setProblemSolved(icp.problem_solved_description || '')
        setVisualDescription(icp.visual_description || '')
        setIcpInfo(icp)
        
        // Helper to format array elements
        function mtusps(val: any) {
          if (Array.isArray(val)) return val.join(', ')
          return String(val || '')
        }
        
        setStep(2)
        // Clear preview so it doesn't persist forever
        localStorage.removeItem('czero_product_preview')
        return
      } catch (e) {
        console.error("Error parsing preview context:", e)
      }
    }

    // 2. Fallback to load the active workspace product details
    const storedProduct = localStorage.getItem('czero_product')
    if (storedProduct) {
      try {
        const product = JSON.parse(storedProduct)
        if (product.url) {
          setUrl(product.url)
          setName(product.name || '')
          setDescription(product.description || '')
          setCompetitors(product.competitor_names ? product.competitor_names.join(', ') : '')
          setSubreddits(product.subreddit_list ? product.subreddit_list.join(', ') : 'SaaS, startups')
          setKeywords(product.keywords ? product.keywords.join(', ') : '')
          
          const icp = product.icp || {}
          setIsNiche(icp.is_niche || false)
          setUsps(icp.usps ? (Array.isArray(icp.usps) ? icp.usps.join(', ') : String(icp.usps)) : '')
          setProblemSolved(icp.problem_solved_description || '')
          setVisualDescription(icp.visual_description || '')
          setIcpInfo(icp)
          
          setStep(2) // Skip Step 1 since we already have product configurations
        }
      } catch (e) {
        console.error("Error parsing stored product config:", e)
      }
    }
  }, [])

  const handleResetForNewScan = () => {
    // Clear localStorage and redirect to Home URL scan page
    localStorage.removeItem('czero_product')
    localStorage.removeItem('czero_product_preview')
    router.push('/dashboard/home')
  }

  // Handle uploaded product screenshot conversion to base64
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) {
      setScreenshotName(file.name)
      const reader = new FileReader()
      reader.onloadend = () => {
        setScreenshot(reader.result as string)
      }
      reader.readAsDataURL(file)
    }
  }

  // Analyze URL to build the Product Context
  const handleAnalyzeURL = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    setError('')
    setSuccess('')

    try {
      const response = await fetch('http://localhost:8000/api/products/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url, screenshot })
      })

      if (!response.ok) {
        throw new Error('Failed to analyze landing page. Make sure the URL is valid.')
      }

      const data = await response.json()
      
      // Pre-fill state with LLM analyzed product data
      setName(data.name || '')
      setDescription(data.description || '')
      setCompetitors('') // Explicitly empty - take user input only
      setSubreddits(data.subreddit_list ? data.subreddit_list.join(', ') : 'SaaS, startups')
      setKeywords(data.keywords ? data.keywords.join(', ') : '')
      
      // Deep context items
      setUsps(data.icp?.usps ? data.icp.usps.join(', ') : '')
      setProblemSolved(data.icp?.problem_solved_description || '')
      setVisualDescription(data.icp?.visual_description || '')

      setIcpInfo(data.icp || null)
      setStep(2) // Move to review step
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Something went wrong')
    } finally {
      setLoading(false)
    }
  }

  // Trigger full pipeline with approved profile
  const handleStartMonitoring = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    setError('')
    setSuccess('')

    try {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) {
        setError('Not logged in')
        setLoading(false)
        return
      }

      // Build structured deep ICP payload
      const payload = {
        user_id: user.id,
        url: url,
        name: name,
        description: description,
        keywords: keywords.split(',').map(k => k.trim()).filter(k => k),
        competitor_names: competitors.split(',').map(c => c.trim()).filter(c => c),
        subreddit_list: subreddits.split(',').map(s => s.trim()).filter(s => s),
        icp: {
          ...(icpInfo || {}),
          is_niche: isNiche,
          usps: usps.split(',').map(u => u.trim()).filter(u => u),
          problem_solved_description: problemSolved,
          visual_description: visualDescription
        }
      }

      const response = await fetch('http://localhost:8000/api/products/setup', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      })

      if (!response.ok) {
        throw new Error('Failed to save configuration context and start monitoring')
      }

      const data = await response.json()

      // Save product context to localStorage
      localStorage.setItem('czero_product', JSON.stringify(data.product || {}))
      // Clear old cached leads to force a fresh DB query on dashboard
      localStorage.removeItem('czero_leads')
      localStorage.removeItem('czero_stats')

      setSuccess(`AI monitoring configured successfully! Initial scan is running in background. Redirecting...`)

      setTimeout(() => {
        router.push('/dashboard')
      }, 2000)

    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Something went wrong')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-canvas text-obsidian-ink flex flex-col antialiased">
      {/* Onboarding Container */}
      <main className="flex-1 flex items-center justify-center p-6 sm:p-12">
        <div className="max-w-2xl w-full bg-white border border-obsidian-ink/10 rounded-lg p-8 sm:p-12 relative my-8">
          
          <div className="mb-8">
            <div className="text-[11px] font-bold text-iris-pulse uppercase tracking-wider mb-2">
              Setup Workspace • Step {step} of 2
            </div>
            <h1 className="text-4xl font-display tracking-tight text-obsidian-ink mb-3 leading-[1.1]">
              {step === 1 ? "Product Scan" : "Review Context Profile"}
            </h1>
            <p className="text-fog text-[14px] leading-relaxed max-w-lg">
              {step === 1 
                ? "Enter your landing page URL. We'll automatically scan it to extract your product scope, ICP, and target subreddits." 
                : "Review and edit the AI-generated product report below to align search queries before monitoring."
              }
            </p>
          </div>

          {error && (
            <div className="bg-red-50 border border-red-200 text-red-600 p-4 rounded-lg text-xs font-medium mb-6">
              <span className="font-bold mr-1">Error:</span> {error}
            </div>
          )}

          {success && (
            <div className="bg-emerald-50 border border-emerald-200 text-emerald-600 p-4 rounded-lg text-xs font-medium mb-6">
              <span className="font-bold mr-1">Success:</span> {success}
            </div>
          )}

          {/* STEP 1: Enter Product URL */}
          {step === 1 && (
            <form onSubmit={handleAnalyzeURL} className="space-y-6">
              <div>
                <label className="block text-[11px] font-bold uppercase tracking-wider text-obsidian-ink mb-2">
                  Product Landing Page URL
                </label>
                <input
                  type="url"
                  value={url}
                  onChange={(e) => setUrl(e.target.value)}
                  placeholder="https://your-saas.com"
                  className="w-full p-3.5 bg-white border border-obsidian-ink/20 focus:border-obsidian-ink rounded-lg text-obsidian-ink placeholder-fog/60 focus:outline-none transition text-sm"
                  required
                  disabled={loading}
                />
              </div>

              {/* Optional Screenshot Vision Uploader */}
              <div>
                <label className="block text-[11px] font-bold uppercase tracking-wider text-obsidian-ink mb-2">
                  Product UI Screenshot (Optional)
                </label>
                <div className="border border-dashed border-obsidian-ink/20 rounded-lg p-6 text-center hover:border-obsidian-ink/40 transition bg-canvas/30 relative">
                  <input
                    type="file"
                    accept="image/*"
                    onChange={handleFileChange}
                    className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                    disabled={loading}
                  />
                  <div className="space-y-1">
                    <div className="text-xs font-semibold text-obsidian-ink">
                      {screenshotName ? `Selected: ${screenshotName}` : "Click to upload product screenshot"}
                    </div>
                    <p className="text-[10px] text-fog">
                      Ingests the UI via Vision LLM to extract visual look, design complexity, and dashboard layout features.
                    </p>
                  </div>
                </div>
              </div>

              <div>
                <label className="block text-[11px] font-bold uppercase tracking-wider text-obsidian-ink mb-2">
                  Market Type
                </label>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <button
                    type="button"
                    onClick={() => setIsNiche(false)}
                    className={`p-4 rounded-lg border text-sm text-left transition flex flex-col justify-between h-[100px] ${
                      !isNiche 
                        ? 'bg-iris-pulse/5 border-iris-pulse text-iris-pulse' 
                        : 'bg-white border-obsidian-ink/15 text-fog hover:border-obsidian-ink/40'
                    }`}
                  >
                    <span className="font-bold">General Market</span>
                    <span className={`text-[11px] mt-1 leading-normal ${!isNiche ? 'text-iris-pulse/80' : 'text-fog/80'}`}>
                      AI, CRM, DevTools (1-day monitor window)
                    </span>
                  </button>
                  <button
                    type="button"
                    onClick={() => setIsNiche(true)}
                    className={`p-4 rounded-lg border text-sm text-left transition flex flex-col justify-between h-[100px] ${
                      isNiche 
                        ? 'bg-iris-pulse/5 border-iris-pulse text-iris-pulse' 
                        : 'bg-white border-obsidian-ink/15 text-fog hover:border-obsidian-ink/40'
                    }`}
                  >
                    <span className="font-bold">Niche Market</span>
                    <span className={`text-[11px] mt-1 leading-normal ${isNiche ? 'text-iris-pulse/80' : 'text-fog/80'}`}>
                      Rare tech stack, narrow focus (7-day monitor window)
                    </span>
                  </button>
                </div>
              </div>

              <button
                type="submit"
                disabled={loading}
                className="w-full py-3.5 bg-obsidian-ink hover:bg-obsidian-ink/95 text-white font-medium rounded-full disabled:opacity-50 flex items-center justify-center transition shadow-sm text-sm"
              >
                {loading ? (
                  <span className="flex items-center space-x-2">
                    <svg className="animate-spin h-4 w-4 text-white" viewBox="0 0 24 24" fill="none">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                    </svg>
                    <span>Analyzing landing page & vision content...</span>
                  </span>
                ) : (
                  <>Scan Landing Page <span className="ml-1">→</span></>
                )}
              </button>
            </form>
          )}

          {/* STEP 2: Review and Edit Profile */}
          {step === 2 && (
            <form onSubmit={handleStartMonitoring} className="space-y-6">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-[11px] font-bold uppercase tracking-wider text-obsidian-ink mb-1.5">
                    Product Name
                  </label>
                  <input
                    type="text"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    className="w-full p-3 bg-white border border-obsidian-ink/20 focus:border-obsidian-ink rounded-lg text-obsidian-ink focus:outline-none transition text-sm"
                    required
                  />
                </div>

                <div>
                  <label className="block text-[11px] font-bold uppercase tracking-wider text-obsidian-ink mb-1.5">
                    Competitor Brands
                  </label>
                  <p className="text-[9px] text-fog mb-1">
                    Enter direct commercial competitors manually (comma-separated).
                  </p>
                  <input
                    type="text"
                    value={competitors}
                    onChange={(e) => setCompetitors(e.target.value)}
                    placeholder="e.g. Browserbase, MultiOn, Skyvern"
                    className="w-full p-3 bg-white border border-obsidian-ink/20 focus:border-obsidian-ink rounded-lg text-obsidian-ink focus:outline-none transition text-sm"
                  />
                </div>
              </div>

              <div>
                <label className="block text-[11px] font-bold uppercase tracking-wider text-obsidian-ink mb-1.5">
                  Product Description
                </label>
                <textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  rows={2}
                  className="w-full p-3 bg-white border border-obsidian-ink/20 focus:border-obsidian-ink rounded-lg text-obsidian-ink focus:outline-none transition text-sm resize-none leading-relaxed"
                  required
                />
              </div>

              {/* Deep Context USPs */}
              <div>
                <label className="block text-[11px] font-bold uppercase tracking-wider text-obsidian-ink mb-1.5">
                  Unique Selling Propositions (USPs)
                </label>
                <p className="text-[9px] text-fog mb-1">
                  Key differentiators that stand out to buyers (comma-separated).
                </p>
                <input
                  type="text"
                  value={usps}
                  onChange={(e) => setUsps(e.target.value)}
                  placeholder="e.g. Bypasses Cloudflare, 24/7 API sweeps, Free trial"
                  className="w-full p-3 bg-white border border-obsidian-ink/20 focus:border-obsidian-ink rounded-lg text-obsidian-ink focus:outline-none transition text-sm"
                />
              </div>

              {/* In-depth Problem Solved */}
              <div>
                <label className="block text-[11px] font-bold uppercase tracking-wider text-obsidian-ink mb-1.5">
                  Detailed Problem Solved
                </label>
                <textarea
                  value={problemSolved}
                  onChange={(e) => setProblemSolved(e.target.value)}
                  rows={2}
                  className="w-full p-3 bg-white border border-obsidian-ink/20 focus:border-obsidian-ink rounded-lg text-obsidian-ink focus:outline-none transition text-sm resize-none leading-relaxed"
                />
              </div>

              {/* AI Vision UI Description */}
              {visualDescription && (
                <div>
                  <label className="block text-[11px] font-bold uppercase tracking-wider text-obsidian-ink mb-1.5">
                    Product Visual look & complexity (AI Vision)
                  </label>
                  <textarea
                    value={visualDescription}
                    onChange={(e) => setVisualDescription(e.target.value)}
                    rows={2}
                    className="w-full p-3 bg-white border border-obsidian-ink/20 focus:border-obsidian-ink rounded-lg text-obsidian-ink focus:outline-none transition text-sm resize-none leading-relaxed bg-zinc-50"
                  />
                </div>
              )}

              {/* Target ICP Context Summary */}
              {icpInfo && (
                <div className="bg-obsidian-ink/5 border border-obsidian-ink/10 p-4 rounded-lg space-y-2 text-xs">
                  <h4 className="font-bold uppercase tracking-wider text-obsidian-ink">Ideal Customer Profile (ICP)</h4>
                  <div>
                    <span className="font-bold text-fog uppercase tracking-wide mr-1.5">Audience:</span>
                    <span className="text-obsidian-ink">{icpInfo.target_audience}</span>
                  </div>
                  <div>
                    <span className="font-bold text-fog uppercase tracking-wide mr-1.5">Pain Point:</span>
                    <span className="text-obsidian-ink">{icpInfo.pain_point_solved}</span>
                  </div>
                </div>
              )}

              <div>
                <label className="block text-[11px] font-bold uppercase tracking-wider text-obsidian-ink mb-1.5">
                  Subreddits to Monitor
                </label>
                <p className="text-[9px] text-fog mb-1">
                  AI suggested specific subreddits. Edit or add more.
                </p>
                <input
                  type="text"
                  value={subreddits}
                  onChange={(e) => setSubreddits(e.target.value)}
                  className="w-full p-3 bg-white border border-obsidian-ink/20 focus:border-obsidian-ink rounded-lg text-obsidian-ink focus:outline-none transition text-sm"
                  required
                />
              </div>

              <div>
                <label className="block text-[11px] font-bold uppercase tracking-wider text-obsidian-ink mb-1.5">
                  Buyer-Intent Search Queries
                </label>
                <p className="text-[10px] text-fog mb-2 leading-relaxed">
                  These queries are scanned across social engines to match intent leads. Edited terms must be comma-separated.
                </p>
                <textarea
                  value={keywords}
                  onChange={(e) => setKeywords(e.target.value)}
                  rows={3}
                  className="w-full p-3 bg-white border border-obsidian-ink/20 focus:border-obsidian-ink rounded-lg text-obsidian-ink focus:outline-none transition text-[13px] leading-relaxed resize-y"
                  required
                />
              </div>

              <div className="flex space-x-3 pt-2">
                <button
                  type="button"
                  onClick={() => setStep(1)}
                  className="px-6 py-3 bg-white border border-obsidian-ink text-obsidian-ink hover:bg-obsidian-ink hover:text-white font-medium rounded-full transition text-sm"
                >
                  Back
                </button>

                <button
                  type="submit"
                  disabled={loading}
                  className="flex-1 py-3 bg-obsidian-ink hover:bg-obsidian-ink/90 text-white font-medium rounded-full disabled:opacity-50 flex items-center justify-center transition shadow-sm text-sm"
                >
                  {loading ? (
                    <span className="flex items-center space-x-2">
                      <svg className="animate-spin h-4 w-4 text-white" viewBox="0 0 24 24" fill="none">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                      </svg>
                      <span>Configuring Scan...</span>
                    </span>
                  ) : (
                    <>Approve & Launch Scan <span className="ml-1">→</span></>
                  )}
                </button>
              </div>
              <div className="text-center pt-4 border-t border-obsidian-ink/10 mt-6">
                <button
                  type="button"
                  onClick={handleResetForNewScan}
                  className="text-xs text-iris-pulse hover:underline font-semibold"
                >
                  Scan a new Landing Page URL instead
                </button>
              </div>
            </form>
          )}
        </div>
      </main>
    </div>
  )
}
